# Generated by Django 5.1.3 on 2025-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='blog/', verbose_name='عکس'),
            preserve_default=False,
        ),
    ]
